import React from 'react';

export const FooterDisclaimer: React.FC = () => {
    return (
        <footer className="w-full bg-gray-50 border-t border-gray-200 mt-12 py-8 px-4">
            <div className="max-w-4xl mx-auto text-center">
                <h4 className="text-sm font-bold text-gray-700 uppercase tracking-wider mb-2">⚠️❗ Important Disclaimer</h4>
                <p className="text-xs text-gray-500 leading-relaxed">
                    The information and analysis provided by this application are for <strong>educational and informational purposes only</strong>.
                    This report is generated by an Artificial Intelligence system and does not constitute professional financial advice,
                    investment recommendations, or legal counsel. Financial markets are volatile and involve significant risk.
                    Past performance is not indicative of future results. You should not rely solely on this information for making
                    financial decisions. We strongly recommend consulting with a qualified, certified financial planner or advisor
                    before making any investment decisions. The developer and the AI provider assume no responsibility for any
                    losses or damages resulting from the use of this tool.
                </p>
            </div>
        </footer>
    );
};